# Generated by Django 4.0.2 on 2022-07-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('post_image', models.ImageField(null=True, upload_to='uploads/pictures_posted')),
                ('description', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('profile_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
