# Generated by Django 4.0.2 on 2022-05-17 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('likes', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_imgs', models.ImageField(upload_to='uploads/pictures_posted')),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
