# Generated by Django 4.0.2 on 2022-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_profile_posts_profile_name_remove_posts_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_imgs',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pictures_posted'),
        ),
    ]
