# Generated by Django 4.0.2 on 2022-06-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_phone_number'),
        ('posts', '0004_alter_posts_published_imgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='published_imgs',
            new_name='post_image',
        ),
        migrations.AlterField(
            model_name='posts',
            name='profile_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile'),
        ),
    ]
